services:
  frontend:
    build: .
    command: pnpm --filter app dev
    develop:
      watch:
        - action: sync
          path: app
          target: /walking/app
          ignore:
            - node_modules

        - action: rebuild
          path: app/package.json
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: .dockerignore

    ports:
      - 5173:5173

    volumes:
      - pnpm_cache:/pnpm/store

volumes:
  pnpm_cache:
